# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99d2d32617e282b402b86939f760c68a5020493813cb333b6345dfd9b306b4a6ddef39adbbcbea19eaf68489af3b44a8e4b60808206e4d711fa42e71503d6a8d

test:
  secret_key_base: b1d45eb5a294c932c0bd3e059f015f54e8f9b2c7362306a7262723b0cf4eddd5a3c4f04984041af8088fe029fa62a7d85af375941c3dee16917993883285bd3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
